services:
  - type: web
    name: cozmo-discord-bot
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: SPORTS_API_KEY
        sync: false
      - key: NEWS_CHANNEL_ID
        sync: false